name       : qml-box2d
version    : 2018.01.09
release    : 2
source     :
    - git|https://github.com/qml-box2d/qml-box2d : 21e57f1c0fbf6e65072c269f89d98a94ed5d7f7f
license    : GPL-3.0-or-later
component  : programming.library
summary    : Box2D QML plugin
description: |
    The goal of the qml-box2d plugin is to expose the functionality of Box2D (C++) as a QML plugin in order to make it easier to write physics based software in QML.
builddeps  :
    - pkgconfig(Qt5Qml)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
